package yuck.flatzinc.test.util

object HasGlobalConstraint {
    final val HasAllDifferentConstraint = "HasAllDifferentConstraint"
    final val HasAllDifferentExceptConstraint = "HasAllDifferentExceptConstraint"
    final val HasAtLeastConstraint = "HasAtLeastConstraint"
    final val HasAtMostConstraint = "HasAtMostConstraint"
    final val HasBinPackingConstraint = "HasBinPackingConstraint"
    final val HasCircuitConstraint = "HasCircuitConstraint"
    final val HasConnectedConstraint = "HasConnectedConstraint"
    final val HasCountConstraint = "HasCountConstraint"
    final val HasCumulativeConstraint = "HasCumulativeConstraint"
    final val HasDecreasingConstraint = "HasDecreasingConstraint"
    final val HasDeliveryConstraint = "HasDeliveryConstraint"
    final val HasDiffnConstraint = "HasDiffnConstraint"
    final val HasDisjunctiveConstraint = "HasDisjunctiveConstraint"
    final val HasElementConstraint = "HasElementConstraint"
    final val HasExactlyConstraint = "HasExactlyConstraint"
    final val HasGlobalCardinalityConstraint = "HasGlobalCardinalityConstraint"
    final val HasIncreasingConstraint = "HasIncreasingConstraint"
    final val HasInverseConstraint = "HasInverseConstraint"
    final val HasKnapsackConstraint = "HasKnapsackConstraint"
    final val HasLexLessConstraint = "HasLexLessConstraint"
    final val HasLexLessEqConstraint = "HasLexLessEqConstraint"
    final val HasMaximumConstraint = "HasMaximumConstraint"
    final val HasMemberConstraint = "HasMemberConstraint"
    final val HasNetworkFlowCostConstraint = "HasNetworkFlowCostConstraint"
    final val HasMinimumConstraint = "HasMinimumConstraint"
    final val HasNValueConstraint = "HasNValueConstraint"
    final val HasRegularConstraint = "HasRegularConstraint"
    final val HasSlidingSumConstraint = "HasSlidingSumConstraint"
    final val HasSubcircuitConstraint = "HasSubcircuitConstraint"
    final val HasTableConstraint = "HasTableConstraint"
    final val HasValuePrecedeConstraint = "HasValuePrecedeConstraint"
    final val HasValuePrecedeChainConstraint = "HasValuePrecedeChainConstraint"
}
