package yuck.flatzinc.test.util

/**
 * @author Michael Marte
 *
 */
trait HasGlobalConstraint

trait HasAlldifferentConstraint extends HasGlobalConstraint
trait HasAlldifferentExcept0Constraint extends HasGlobalConstraint
trait HasAtLeastConstraint extends HasGlobalConstraint
trait HasAtMostConstraint extends HasGlobalConstraint
trait HasBinPackingConstraint extends HasGlobalConstraint
trait HasCircuitConstraint extends HasGlobalConstraint
trait HasCountConstraint extends HasGlobalConstraint
trait HasCumulativeConstraint extends HasGlobalConstraint
trait HasDecreasingConstraint extends HasGlobalConstraint
trait HasDeliveryConstraint extends HasGlobalConstraint
trait HasDiffnConstraint extends HasGlobalConstraint
trait HasDisjunctiveConstraint extends HasGlobalConstraint
trait HasElementConstraint extends HasGlobalConstraint
trait HasExactlyConstraint extends HasGlobalConstraint
trait HasGlobalCardinalityConstraint extends HasGlobalConstraint
trait HasIncreasingConstraint extends HasGlobalConstraint
trait HasInverseConstraint extends HasGlobalConstraint
trait HasKnapsackConstraint extends HasGlobalConstraint
trait HasLexLessConstraint extends HasGlobalConstraint
trait HasLexLessEqConstraint extends HasGlobalConstraint
trait HasMaximumConstraint extends HasGlobalConstraint
trait HasMemberConstraint extends HasGlobalConstraint
trait HasNetworkFlowCostConstraint extends HasGlobalConstraint
trait HasMinimumConstraint extends HasGlobalConstraint
trait HasNValueConstraint extends HasGlobalConstraint
trait HasRegularConstraint extends HasGlobalConstraint
trait HasSubcircuitConstraint extends HasGlobalConstraint
trait HasTableConstraint extends HasGlobalConstraint
trait HasValuePrecedeConstraint extends HasGlobalConstraint
