package yuck.core

import scala.collection.*

/**
 * Defines a neighbourhood for local search.
 *
 * @author Michael Marte
 */
abstract class Neighbourhood {

    protected val space: Space

    /** Returns the variables that may occur in the moves produced by this neighbourhood. */
    def searchVariables: Set[AnyVariable]

    /** Returns the children of this neighbourhood. */
    def children: Iterable[Neighbourhood]

    /** Creates a move. */
    def nextMove(): Move

    /**
     * Notifies this neighbourhood that search has decided for the given move.
     *
     * Only to be called with the move that was generated by the most recent call
     * to nextMove on this neighbourhood.
     *
     * The default implementation does nothing.
     */
    def commit(move: Move): Unit = {}

    /**
     * Perturbs the assignment to the variables governed by this neighbourhood.
     */
    def perturb(perturbationProbability: Probability): Unit = {
        for (i <- 0 until (searchVariables.size * perturbationProbability.value).ceil.toInt) {
            val move = nextMove()
            space.consult(move)
            space.commit(move)
            commit(move)
        }
    }

}
