package yuck.core

import scala.collection.*

/**
 * Defines a neighbourhood for local search.
 *
 * @author Michael Marte
 */
abstract class Neighbourhood {

    /** Returns the variables that may occur in the moves produced by this neighbourhood. */
    def searchVariables: Set[AnyVariable]

    /** Returns the children of this neighbourhood. */
    def children: Iterable[Neighbourhood]

    /** Creates a move. */
    def nextMove: Move

    /**
     * Notifies this neighbourhood that search has decided for the given move.
     *
     * Only to be called with the move that was generated by the most recent call
     * to nextMove on this neighbourhood.
     *
     * The default implementation does nothing.
     */
    def commit(move: Move): Unit = {}

}
