----------
timetabling:
course sections assigned (1 row per student, 1 col per course):
1 1 1 1
1 1 1 2
1 3 1 1
1 1 1 3
1 1 1 2
1 1 1 1
1 1 1 3
1 2 1 1
1 1 1 1
1 1 1 1
1 1 1 1
1 1 1 3
1 1 1 1
1 1 1 1
1 1 1 2
1 1 1 1
1 1 1 2
1 1 1 1
1 1 1 1
1 1 1 1
times of each section (1 row per course, 1 col per section):
1 5 2
5 1 1
4 1 1
3 1 1
2 1 1
1 1 1
=== NO MORE SOLUTIONS ===
Search incomplete:
  timetabling: commit to first solution
